development:
  adapter: postgresql
  encoding: unicode
  database: fireside-chat_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: fireside-chat_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: fireside-chat_production
  pool: 5
